scheme: Pisces

custom_file_path:
  bodyEnd: source/_data/body-end.njk
  style: source/_data/styles.styl

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  categories: /categories/ || fa fa-th
  tags: /tags/ || fa fa-tags
  about: /about/ || fa fa-user
  resources: /resources/ || fa fa-book

social:
  GitHub: https://github.com/xqcherry || fab fa-github
  E-Mail: mailto:xqcherry@foxmail.com || fa fa-envelope

favicon:
  small:
  medium:
  apple_touch_icon:
  safari_pinned_tab:

avatar:
  url: /images/avatar.png
  rounded: true
  rotated: false

toc:
  enable: true
  number: true
  wrap: false

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

reading_progress:
  enable: true
  color: '#37c6c0'
  height: 3px

pace:
  enable: true
  color: green
  theme: minimal

local_search:
  enable: false

footer:
  since: 2026
  icon:
    name: fa fa-heart
    animated: false
    color: '#808080'
  copyright: xqcherry
  powered: false
